### PR TITLE
compilation fix

### PR DESCRIPTION
**Pull request by michalkucharczyk**
fixing following error (introduced in #57):
```
error: the item `ToString` is imported redundantly
  --> src/lib.rs:48:26
error: the item `Vec` is imported redundantly
  --> src/lib.rs:48:44

error: could not compile `bip39` (lib) due to 2 previous errors
```

### CODE REVIEW

**Comment by michalkucharczyk** [comment]
cc: @stevenroose @tcharding

**Review by tcharding — COMMENTED** [review]
This is just lint warnings, right? @stevenroose is in the process of releasing right now so I'm not sure this will go in. Thanks for coming back to do the fix!

File: src/lib.rs [hunk 1]
```diff
@@ -45,7 +45,7 @@ pub extern crate rand_core;
 pub extern crate serde;
 
 #[cfg(feature = "alloc")]
-use alloc::{borrow::Cow, string::ToString, vec::Vec};
+use alloc::{borrow::Cow};
```
Comment (tcharding) [inline src/lib.rs:48]:
```suggestion
use alloc::borrow::Cow;
```

**Comment by michalkucharczyk** [comment]
> This is just lint warnings, right? @stevenroose is in the process of releasing right now so I'm not sure this will go in. Thanks for coming back to do the fix!

Actually compilation error, CI failed with new rustc version:
https://github.com/rust-bitcoin/rust-bip39/actions/runs/8472579312/job/23214974279

**Comment by michalkucharczyk** [comment]
This PR breaks compilation with older compilers. I did not catch that earlier.

**Comment by michalkucharczyk** [comment]
It is not a compiler problem as I stated in previous comment.
This command will fail:
```
cargo build --release --no-default-features  --features=alloc --lib
```

Error message I see is:
```
error[E0412]: cannot find type `Vec` in this scope
   --> src/lib.rs:107:26
    |
107 |     pub fn to_vec(&self) -> Vec<Language> {
    |                             ^^^ not found in this scope
    |
help: consider importing this struct
    |
47  + use alloc::vec::Vec;
    |

error[E0412]: cannot find type `Vec` in this scope
   --> src/lib.rs:608:30
    |
608 |     pub fn to_entropy(&self) -> Vec<u8> {
    |                                 ^^^ not found in this scope
    |
help: consider importing this struct
    |
47  + use alloc::vec::Vec;
    |

error[E0599]: no method named `to_string` found for struct `Decompositions` in the current scope
    --> src/lib.rs:198:42
     |
198  |             *cow = Cow::Owned(cow.as_ref().nfkd().to_string());
     |                                                   ^^^^^^^^^ method not found in `Decompositions<Chars<'_>>`
     |
    ::: /home/miszka/.rustup/toolchains/1.75.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:2589:8
     |
2589 |     fn to_string(&self) -> String;
     |        --------- the method is available for `Decompositions<Chars<'_>>` here
     |
     = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
     |
29   + use crate::alloc::string::ToString;
     |
```

All checks in `contrib/test.sh` are fine because of this line:
https://github.com/rust-bitcoin/rust-bip39/blob/b100bf3e22891498cb6e0b1c53fd629dab7b34de/Cargo.toml#L57


As the result the crate cannot be used as a dep w/o `std`.

@tcharding @stevenroose do you think we can still have a fix 2.1.0?

**Comment by tcharding** [comment]
This is all caused by a recent rustc upgrade, here is an issue where we are discussing it in `rust-bitcoin`: https://github.com/rust-bitcoin/rust-bitcoin/issues/2653

I'll push a fix, can we get a point release @stevenroose?

**Comment by michalkucharczyk** [comment]
> @michalkucharczyk are you seeing errors on `master`?

Yes. Just run this on master:
```
cargo build --release --no-default-features  --features=alloc --lib
```

This happens for both:
```
rustc --version
rustc 1.75.0 (82e1608df 2023-12-21)
```
and:
```
rustc --version
rustc 1.79.0-nightly (c9f8f3438 2024-03-27)
```

**Comment by tcharding** [comment]
Bizzare, I am not getting errors with
```bash
$ cargo +nightly --version
cargo 1.79.0-nightly (a59aba136 2024-03-28)
$ cargo +nightly build --release --no-default-features  --features=alloc --lib
```

Nor with
```bash
$ cargo --version
cargo 1.77.1 (e52e36006 2024-03-26)
$ cargo build --release --no-default-features  --features=alloc --lib
```

No clue what is going on.

**Comment by michalkucharczyk** [comment]
dq: did you try `cargo clean`? Can you add `-vvv` and attach the output?

The other way to reproduce is creating a simple crate with bip39 as dep. Following the steps listed below generates the same error for me:
```
cargo new rust-bip39-dep-problem2
pushd rust-bip39-dep-problem2
cargo add bip39 --git "https://github.com/rust-bitcoin/rust-bip39"  --rev b100bf3 --no-default-features --features alloc
cargo build
```

**Comment by michalkucharczyk** [comment]
> Bizzare, I am not getting errors with

Wow, seems I am the wombat :) I had commented this line in `Cargo.toml`:
https://github.com/rust-bitcoin/rust-bip39/blob/b100bf3e22891498cb6e0b1c53fd629dab7b34de/Cargo.toml#L57

But you should be able to reproduce problem with the commands I provided in my previous comment.

**Comment by michalkucharczyk** [comment]
fix proposed in: https://github.com/rust-bitcoin/rust-bip39/pull/69

**Comment by tcharding** [comment]
Oh boy, took me so long to work out that the `bip39` path dev-dependency you mention above is enabling "std", and that is why I couldn't get the build warnings.
